---
- name: "{{ ansible_distribution }} - Ensure Hashicorp repository is present."
  yum_repository:
    name: HashiCorp
    description: HashiCorp Repository
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    mirrorlist: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    gpgcheck: false
    enabled: true

- name: "{{ ansible_distribution }} - Ensure packages are present."
  yum:
    name: "{{ hashicorp_product_selection }}"
    state: present
