---
- name: "{{ ansible_distribution }} - Ensure Hashicorp repository is present."
  yum_repository:
    name: HashiCorp
    description: HashiCorp Repository
    baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable"
    gpgcheck: false
    enabled: true

- name: "{{ ansible_distribution }} - Ensure packages are present."
  dnf:
    name: "{{ hashicorp_product_selection }}"
    state: present
