---
- name: "Ensure the HashiCorp repository is present."
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    owner: root
    group: root
    mode: "0644"

- name: "Ensure requested HashiCorp packages are present."
  ansible.builtin.dnf:
    name: "{{ item.name }}{{ ('-' ~ item.version ~ '*') if item.version | default('latest') != 'latest' else '' }}"
    state: present
  loop: "{{ hashicorp_products }}"
  loop_control:
    label: "{{ item.name }}{{ (' (' ~ item.version ~ ')') if item.version is defined else '' }}"
