---
- name: "{{ ansible_distribution }} - Ensure that Hashicorp signing key is present."
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: all, consul, nomad, terraform, vault

- name: "{{ ansible_distribution }} - Ensure that Hashicorp repository is present."
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  tags: all, consul, nomad, terraform, vault

- name: "{{ ansible_distribution }} - Ensure that apt is updated."
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: all, consul, nomad, terraform, vault

- name: "{{ ansible_distribution }} - Install Consul."
  apt:
    name: consul
    state: present
  tags: all, consul

- name: "{{ ansible_distribution }} - Install Nomad."
  apt:
    name: nomad
    state: present
  tags: all, nomad

- name: "{{ ansible_distribution }} - Install Terraform."
  apt:
    name: terraform
    state: present
  tags: all, terraform

- name: "{{ ansible_distribution }} - Install Vault."
  apt:
    name: vault
    state: present
  tags: all, vault
