---
- name: "{{ ansible_distribution }} - Ensure that Hashicorp repository is present."
  yum_repository:
    name: HashiCorp
    description: HashiCorp Repository
    baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable"
    gpgcheck: false
    enabled: true

- name: "{{ ansible_distribution }} - Install Consul."
  dnf:
    name: consul
    state: present
  when: '"consul" in hashicorp_product_selection'

- name: "{{ ansible_distribution }} - Install Nomad."
  dnf:
    name: nomad
    state: present
  when: '"nomad" in hashicorp_product_selection'

- name: "{{ ansible_distribution }} - Install Terraform."
  dnf:
    name: terraform
    state: present
  when: '"terraform" in hashicorp_product_selection'

- name: "{{ ansible_distribution }} - Install Vault."
  dnf:
    name: vault
    state: present
  when: '"vault" in hashicorp_product_selection'
