---
- name: "{{ ansible_distribution }} - Ensure that Hashicorp repository is present."
  yum_repository:
    name: HashiCorp
    description: HashiCorp Repository
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    mirrorlist: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    gpgcheck: false
    enabled: true

- name: "{{ ansible_distribution }} - Install Consul."
  yum:
    name: consul
    state: present
  when: '"consul" in product_selection'

- name: "{{ ansible_distribution }} - Install Nomad."
  yum:
    name: nomad
    state: present
  when: '"nomad" in product_selection'

- name: "{{ ansible_distribution }} - Install Terraform."
  yum:
    name: terraform
    state: present
  when: '"terraform" in product_selection'

- name: "{{ ansible_distribution }} - Install Vault."
  yum:
    name: vault
    state: present
  when: '"vault" in product_selection'
