---
- name: "{{ ansible_distribution }} - Ensure that Hashicorp repository is present."
  yum_repository:
    name: HashiCorp
    description: HashiCorp Repository
    baseurl: "https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable"
    gpgcheck: no
    enabled: yes
  tags: all, consul, nomad, terraform, vault

- name: "{{ ansible_distribution }} - Install Consul."
  dnf:
    name: consul
    state: present
  tags: all, consul

- name: "{{ ansible_distribution }} - Install Nomad."
  dnf:
    name: nomad
    state: present
  tags: all, nomad

- name: "{{ ansible_distribution }} - Install Terraform."
  dnf:
    name: terraform
    state: present
  tags: all, terraform

- name: "{{ ansible_distribution }} - Install Vault."
  dnf:
    name: vault
    state: present
  tags: all, vault
